apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uav-gnn

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-serve.yaml
  - service-serve.yaml

commonLabels:
  app.kubernetes.io/name: uav-gnn
  app.kubernetes.io/part-of: uav-link-quality
