from pathlib import Path

SEED = 42
NUM_UAVS = 6
TIME_STEPS = 100
DT = 1.0

X_LIMIT = (0.0, 500.0)
Y_LIMIT = (0.0, 500.0)
Z_LIMIT = (50.0, 150.0)

VELOCITY_COMPONENT_RANGE = (-8.0, 8.0)
COMM_RANGE = 230.0

SOURCE_ID = 0
DEST_ID = 4

OUTPUT_DIR = Path("output")
NODES_CSV = OUTPUT_DIR / "nodes.csv"
EDGES_CSV = OUTPUT_DIR / "edges.csv"
TRAFFIC_CSV = OUTPUT_DIR / "traffic_log.csv"
NODES_PARQUET = OUTPUT_DIR / "nodes.parquet"
EDGES_PARQUET = OUTPUT_DIR / "edges.parquet"
TRAFFIC_PARQUET = OUTPUT_DIR / "traffic_log.parquet"

PLOTS_DIR = OUTPUT_DIR / "plots"
SAVE_PLOTS = True
TOPOLOGY_SNAPSHOT_STEPS = [0, 25, 50, 75, 99]
FINAL_FRAME_PNG = PLOTS_DIR / "final_frame.png"

PRINT_EVERY = 10

LIVE_SIMULATION = True
LIVE_PAUSE = 0.08
SHOW_NODE_LABELS = True
SHOW_EDGE_LINES = True
HIGHLIGHT_ROUTE = True
FIGSIZE = (11, 8)

CAMERA_ELEV = 24
CAMERA_AZIM = 38
ROTATE_CAMERA = True
CAMERA_AZIM_STEP = 0.35

SHOW_GRID = True
DARK_THEME = False
SHOW_STATUS_BOX = True
SHOW_TRAILS = True
TRAIL_LENGTH = 18
SHOW_VELOCITY_ARROWS = True
VELOCITY_ARROW_SCALE = 2.5

NODE_SIZE_NORMAL = 90
NODE_SIZE_SOURCE = 180
NODE_SIZE_DEST = 180
EDGE_LINE_ALPHA = 0.35
EDGE_LINE_WIDTH = 1.2
ROUTE_LINE_WIDTH = 4.0

MOBILITY_MODEL = "random-waypoint"  # "gauss-markov" or "random-waypoint"

GAUSS_MARKOV_ALPHA = 0.85
GAUSS_MARKOV_MEAN_VELOCITY = (0.0, 0.0, 0.0)
GAUSS_MARKOV_STDDEV = 2.0

RWP_SPEED_RANGE = (3.0, 8.0)
RWP_PAUSE_STEPS = 0
RWP_REACH_THRESHOLD = 2.0

TX_POWER_DBM = 20.0
REFERENCE_PATH_LOSS_DB = 40.0
PATH_LOSS_EXPONENT = 2.2
NOISE_FLOOR_DBM = -90.0
BASE_DELAY_MS = 2.0
DISCONNECTED_DELAY_MS = 50.0
MAX_THROUGHPUT_MBPS = 100.0
