apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: uav-gnn-staging

namePrefix: staging-

patches:
  - target:
      kind: Deployment
      name: uav-gnn-serve
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi

images:
  - name: uav-gnn-serve
    newName: ghcr.io/kaing615/uav-link-quality-routing-support/uav-gnn-serve
    newTag: latest
